### ISSUE TITLE
Seperate web forntent (aka onYOURway-client) from webservice backand

### ISSUE THREAD

**Issue by art-ist** [art-ist/onYOURway#10]
By seperating the app from the service it is going to be easier to contribute or use just one of the components.

**Comment by art-ist** [comment]
See https://github.com/Svakinn/SplitTowel for inspiration.

**Comment by art-ist** [comment]
Still need a plan to not just split up to different VS Projects in one Repo but how to use two Repos, one for each Project (Server, Client) but still would like to manage it in a single VS Solution.
I know that is no issue to devs not using VS but it can simplify a lot for people who do.
*VS = Visual Studio 2013, currently*

**Comment by almereyda** [comment]
Thanks for the explanation of the term VS.
Does it have git support? If yes, one could try the `submodule` approach.
Or publishing the client on an integrated package manager (NuGet, ...?).

**Comment by art-ist** [comment]
Server and client components are in seperate projects now and can be treated independently.
