### ISSUE TITLE
LICENCE.md : How can I reuse this content, if?

### ISSUE THREAD

**Issue by almereyda** [art-ist/onYOURway#9]
GitHub on:

* [Choosing an Open Source Licence](https://github.com/blog/1530-choosing-an-open-source-license)
* [Open Source Licencing](https://help.github.com/articles/open-source-licensing)

**Comment by art-ist** [comment]
See: [LICENCE.md](https://github.com/art-ist/onYOURway/blob/master/LICENCE.md)
